name: momphotos
description: "A photo management app with cloud storage and tagging features."
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ^3.8.1

dependencies:
  image: ^4.0.17
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^1.1.0

  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  exif: ^3.3.0

  # UI components
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^6.0.2

  # State management
  provider: ^6.1.1

  # Routing
  go_router: ^14.2.0
  flutter_web_plugins:
    sdk: flutter

  # Web view for password reset
  webview_flutter: ^4.7.0

  # Web APIs
  web: ^0.5.0

  # Utilities
  intl: ^0.18.1
  path: ^1.9.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.9.1
  
  # Image saving
  image_gallery_saver: ^2.0.3
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_icons:
  ios: true
  android: false
  image_path: "assets/icon/app_icon.png"
  
flutter_native_splash:
  color: "#FEF9F2"  # 背景色，建议与图片协调（此处为淡粉）
  image: assets/icon/launch_splash.png  # 你刚才生成的图片路径
  ios: true
  android: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
