services:
- type: web
  name: momphotos
  env: python
  repo: https://github.com/owenshapw/momphotos
  plan: free
  envVars:
  - key: SUPABASE_KEY
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: PYTHON_VERSION
    value: 3.9.0
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeployTrigger: commit
version: "1"