services:
- type: web
  name: momphotos
  runtime: python
  repo: https://github.com/owenshapw/momphotos
  plan: free
  envVars:
  - key: SUPABASE_KEY
    sync: false
  - key: SUPABASE_URL
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: "gunicorn app:app"
  autoDeployTrigger: commit
version: "1"